select *from customer limit 20;
-- 1. what is teh total revenue generated by the male vs female customers?.

select gender ,sum(purchase_amount) as revenue 
from customer 
group by gender;

-- 2. which customers used the discount but still spent more thna the avg purchase ampount.

select customer_id , purchase_amount from customer where 
discount_applied='Yes' and 
purchase_amount>(select avg(purchase_amount) from customer);

-- 3. which are the top 5 products with the highest avcerage review rating
select item_purchased, round(avg(review_rating)::numeric,2)  as average_Product_rating from customer group by item_purchased 
order by avg(review_rating) desc limit 5;

-- 4. Compare the average purchase amount between Express andStandard Shipping.

select shipping_type , round(avg(purchase_amount),2) as Average_Shipping_amount from customer where shipping_type in ('Express','Standard') group by shipping_type;

-- 5. Do subscribed customer spends more ?Compare average total spent and total revenue between subscribers and non-subscribers. 

select subscription_status , count(customer_id),sum(purchase_amount) as Total_spent , round(avg(purchase_amount),2) as average_amount from customer 
group by subscription_status;

-- 6. Which 5 products have highest percentage of purchases with discount applied ?

select item_purchased as Product, round(100 *sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate from customer
group by item_purchased 
order by discount_rate desc limit 10;

--7. Segment customers into new , Returning and loyal based on their total
--   number of previos purchases and show thc count of each segment.

-- select customer_id , 
-- case
-- when previous_purchases=1  then 'New' 
-- when previous_purchases between 2 and 10 then 'Returning' 
-- else 'Loyal'
-- end as Type_of_customer from customer  group by previous_purchases order by Type_of_customer desc;

with customer_type as (
select customer_id,previous_purchases,
CASE 
     WHEN previous_purchases=1 THEN 'New'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	 ELSE 'Loyal'
	 END as customer_segment
from customer
)
select customer_segment , count(*) as Number_of_customers
from customer_type 
group by customer_segment;


-- 8. What are the 3 most purchased products from each categories ?

with item_count as (
select category , item_purchased , count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by category , item_purchased
)

select item_rank,category , item_purchased ,total_orders 
from item_count where item_rank<=3 ;

-- 9. Are customer who are repeay buyers(more than five previous purchases) also more likely to subscribe?

select subscription_status , count(customer_id) as repeat_buyers 
from customer 
where previous_purchases>5 
group by subscription_status;

-- 10. What is the revenue contribution of each group ?

select age_group , sum(purchase_amount) from customer
group by age_group
order by sum(purchase_amount) desc;







